services:
  postgres:
        image: postgres:16.4
        container_name: postgres
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
          - "${POSTGRES_PORT}:5432"
        volumes:
          - ./.dbdata:/var/lib/postgresql/data